### ISSUE TITLE
How to remove loci with no SNPs?  

### ISSUE THREAD

**Issue by dantylee** [huwenboshi/hess#1]
Could you provide some clarification of how to properly/efficiently remove loci with no SNPs?    This was not obvious to me and I don't want to make mistake.  

My best guess it to go back to the partition (e.g., fourier_ls-chr1.bed) and remove the rows as indicated by the .log file.   However, because I'm assessing many correlations, this would mean generating a new set of partition files for every correlation.  Seems like it could be beneficial to add optional flags --drop-missing-loci in Step 1 and Step 2 of the local genetic correlation routine.   [See below FAQ for context]

[ERROR] Rank of A less than the number of loci. There might be loci with no SNP.    The second step of HESS and \(\rho\)-HESS involves inverting a matrix. If the matrix is not invertible, HESS and \(\rho\)-HESS will not attempt to estimate SNP-heritability or genetic covariance.   Usually, this error is caused by empty locus (SNP with no SNP in it).  If there are empty loci in the data, it is recommended to remove these loci or combine these loci with nearby loci.

**Comment by huwenboshi** [comment]
For now you will need to manually modify the bed files to remove the loci that contain no SNP. We will try to add the --drop-missing-loci functionality some time soon.

**Comment by JingniHe** [comment]
> For now you will need to manually modify the bed files to remove the loci that contain no SNP. We will try to add the --drop-missing-loci functionality some time soon.

I ran into the same issue. How do I know which file that went wrong due to the loci with no SNP issue. My log file did not point out the row or the file that went wrong.  Also, how to delete the corresponding rows in the bed file?? Thanks!

**Comment by Mary-mufford** [comment]
@JingniHe did you find a solution? I am having the same problem

**Comment by adamdoescode** [comment]
@JingniHe and @Mary-mufford and anyone else who finds this issue in the future. Here are the steps I took to resolve this:

The log files from step1 output whether each partition/locus has SNPs or not. You can find all cases where they don't return hits with grep:
`grep -w "0 SNPs in locus" *log`
Your output will look similar to this (but I used ripgrep which is faster than grep):
>sumstats_chr15.log
>25:[INFO] 0 SNPs in locus chr15:20001200-21131604
You can then go into the bed files to edit this. If you use the partition files recommended by Rho.Hess they will be in `nygcresearch-ldetect-data` and then in one of the ancestry folders, for me that was in `EUR`.
You need to delete the lines that match the chromosome and positions, for my particular example I wanted `EUR/fourier_ls-chr15.bed` and the line to delete was:
>chr15 	 20001200 	 21131604

A couple of recommendations:
- You should copy the whole directory and make modifications to the copy so that you have the original for reference and don't accidently use it for unrelated sumstats.
- Do a test run with just the affected chromosomes to save you troubleshooting time since rho.hess takes a while to run

I wonder if it is better to use the same bed files for other sumstats you want to local rg() on? Or should I use the more complete bed file (i.e no deletions) if I can even if the other sumstats has deleted partitions?
