### ISSUE TITLE
Step 2 different total SNP heritability estimates

### ISSUE THREAD

**Issue by MLRodrigu** [huwenboshi/hess#4]
Hello, sorry if the answer is quite obvious but I have a question.

1) Why the total SNP-heritability estimate that appear in the log file is different from the one that I proportionate?

Here is my command, where the total SNP h^2 = 0.2354, SE = 0.0153

python ~/Softwares/hess-0.5.3-beta/hess.py --prefix step1 --tot-hsqg 0.2354 0.0153 --out step2

And here is the log file

[INFO] @----------------------------------------------------------@
       |         HESS       |      v0.5      |    9/October/2017  |
       |----------------------------------------------------------|
       |  (C) 2017 Huwenbo Shi, GNU General Public License, v3    |
       |----------------------------------------------------------|
       |  For documentation, citation & bug-report instructions:  |
       |   http://bogdan.bioinformatics.ucla.edu/software/hess/   |
       @----------------------------------------------------------@
[INFO] Command started at: Thu, 01 Nov 2018 16:51:56
[INFO] Command issued:
    /home/marianar/Softwares/hess-0.5.3-beta/hess.py \
        --tot-hsqg 0.2354 0.0153 \
        --prefix step1 \
        --out step2
[INFO] Loaded results for 1703 loci from step 1
[INFO] Using 4661012 SNPs with average sample size 53293.0
[INFO] Re-inflate the summary statistics with lambda_gc: 1
[INFO] Total SNP-heritability estimate: 0.247 (0.0251)
[INFO] Command finished at: Thu, 01 Nov 2018 16:51:59

But now in the log file it says Total SNP-heritability estimate: 0.247 (0.0251). 
I know is not such a big difference but I have done the same in other traits and some have change too much.

Thanks

**Comment by huwenboshi** [comment]
So sorry to get back to you this late... In general, the total SNP-heritability estimate from step 2 isn't guaranteed to be equal to the total heritability you specified, as there is no constraint on the sum of local estimates to be equal to the value specified with the --tot-hsqg flag. And the discrepancy between the two numbers can come from discrepancies of the underlying model assumptions or different set of SNPs used to estimate heritability. In case you are estimating heritability of case-control traits, the discrepancy could be caused by different proportions of case/control samples or whether you use observed-scale or liability-scale heritability. We also find that the discrepancy tends to be larger for GWAS with very small samples.
